// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plnfmsuuwzuvigjrmara.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbmZtc3V1d3p1dmlnanJtYXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODI4NzIsImV4cCI6MjA3MjE1ODg3Mn0.Ce7ubm_ueNvdibTM1vVDh2p0tLLYIODUYfMPOofn9LY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});